easy_admin:
    entities:    
       Bussines:
            disabled_actions: ['delete']
            class: App\Entity\Bussines
            label: menu.bussines
            list:
                title: menu.bussines
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'name', label: 'name'}

                    

                    

