resources:
    App\Entity\Product:
        attributes:
            normalization_context:
                groups: ['product-read']
            denormalization_context:
                groups: ['product-write']
        collectionOperations:
            get:
                method: 'GET'

            post:
                method: 'POST'

