resources:
    App\Entity\Rate:
        attributes:
            normalization_context:
                groups: ['rate-read']
            denormalization_context:
                groups: ['rate-write']
        collectionOperations:
            get:
                method: 'GET'

            post:
                method: 'POST'

